Human

In [2]:
import cv2
import numpy as np

In [3]:
cv2.__version__

'4.5.5'

In [4]:
# pip install opencv-contrib-python == 4.5.5

ERROR: Invalid requirement: '=='


In [ ]:
# lib.01gl c++ 
#opencv 4.9.8 (error)
#opencv-python-heddless
#The Kernel crashed

In [4]:
img = cv2.imread("./data/human.jpg")

In [5]:
type(img)

numpy.ndarray

In [6]:
copy = img.copy()

In [8]:
cv2.imshow("image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
img.shape

(510, 768, 3)

In [10]:
#mask
mask = np.zeros(img.shape[:2], np.uint8)

In [11]:
#create dummay arrays for future using
bgd = np.zeros((1,65), np.float64)
fgd = np.zeros((1,65), np.float64)

In [12]:
#select ROI
rect = cv2.selectROI(img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
x,y,w,h = rect

In [ ]:
cv2.rectangle(copy, (x,y), (x+w, y+h), (0,0,255), 3)

In [16]:
cv2.imwrite("roi.png", copy)

True

In [ ]:
cv2.grabCut(img, mask, rect, bgd, fgd, 5, cv2.GC_INIT_WITH_RECT)

In [24]:
np.unique(mask)

array([0, 2, 3], dtype=uint8)

In [31]:
mask2 = np.where((mask == 2 ) | (mask == 0), 0, 1).astype("uint8")
cv2.imwrite("mask.png", mask*80)
cv2.imwrite("mask2.png", mask2*255)


True

In [29]:
np.unique(mask)

array([0, 2, 3], dtype=uint8)

In [30]:
np.unique(mask2)

array([0, 1], dtype=uint8)

In [34]:
mask.ndim,mask2.ndim

(2, 2)

In [39]:
#inference on original data (image)

img = img * mask2[:,:,np.newaxis]
cv2.imwrite("result.png", img)

True

Cars